/**
 * Mule Magento Cloud Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

package org.mule.module.magento.api.util;

/**
 * Utility class for determining if a class is a "Magento Class", that is, if it is
 * an axis autogenerated class, based on its package
 */
public final class MagentoClass
{
    private static final String MAGENTO_PACKAGE_NAME = "org.mule.module.magento.api.internal";
    
    private MagentoClass()
    {
    }

    public static boolean isMagentoArrayClass(Class<?> clazz)
    {
        return clazz.isArray() && isMagentoClass(clazz.getComponentType());
    }

    public static boolean isMagentoClass(Class<?> clazz)
    {
        return !clazz.isPrimitive() && !clazz.isArray() && clazz.getName().startsWith(MAGENTO_PACKAGE_NAME);
    }
}
